import React, { useRef, useState } from 'react';
import { PanelData } from '../types';
import { 
  RefreshCw, Download, Pencil, ChevronDown, 
  Loader2, Image as ImageIcon, FileImage, 
  LayoutTemplate, Grid2X2, RectangleVertical, Columns3 
} from 'lucide-react';
import html2canvas from 'html2canvas';

interface ComicCanvasProps {
  panels: PanelData[];
  title: string;
  onRegeneratePanel: (id: number) => void;
  onEditScript: () => void;
}

type LayoutMode = 'grid' | 'vertical' | 'wide';

export const ComicCanvas: React.FC<ComicCanvasProps> = ({ panels, title, onRegeneratePanel, onEditScript }) => {
  const comicRef = useRef<HTMLDivElement>(null);
  const [showSaveMenu, setShowSaveMenu] = useState(false);
  const [showLayoutMenu, setShowLayoutMenu] = useState(false);
  const [isSaving, setIsSaving] = useState(false);
  const [layout, setLayout] = useState<LayoutMode>('grid');

  const handleSave = async (format: 'png' | 'jpeg') => {
    if (!comicRef.current) return;
    
    setIsSaving(true);
    try {
      // Small delay to ensure any UI rendering settles
      await new Promise(resolve => setTimeout(resolve, 100));

      const canvas = await html2canvas(comicRef.current, {
        scale: 2, // Higher resolution
        useCORS: true, // Handle cross-origin images
        logging: false,
        backgroundColor: '#ffffff', // Ensure white background
      });

      const image = canvas.toDataURL(`image/${format}`, 0.9);
      const link = document.createElement('a');
      const filename = `${title.trim().replace(/\s+/g, '-').toLowerCase() || 'comic'}.${format === 'jpeg' ? 'jpg' : 'png'}`;
      
      link.href = image;
      link.download = filename;
      document.body.appendChild(link);
      link.click();
      document.body.removeChild(link);
      
      setShowSaveMenu(false);
    } catch (error) {
      console.error("Failed to save comic:", error);
      alert("Could not save the image. Please try again.");
    } finally {
      setIsSaving(false);
    }
  };

  const getLayoutClasses = () => {
    switch (layout) {
      case 'vertical':
        return "grid-cols-1 max-w-xl mx-auto";
      case 'wide':
        return "grid-cols-1 md:grid-cols-3";
      case 'grid':
      default:
        // Smart grid: if 5 panels, make first one span 2 cols to look nicer
        return "grid-cols-1 md:grid-cols-2";
    }
  };

  // Helper for uneven grids (5 panels in 2 cols)
  const getPanelClasses = (index: number, total: number) => {
    if (layout === 'grid' && total % 2 !== 0 && index === 0) {
       return "md:col-span-2 aspect-[2/1]"; 
    }
    return "aspect-square";
  };
  
  return (
    <div className="max-w-6xl mx-auto w-full p-4 animate-in fade-in duration-700">
      <div className="flex flex-col md:flex-row items-center justify-between mb-8 gap-4">
        <div className="text-center md:text-left">
           <h1 className="text-4xl font-comic text-white tracking-widest uppercase drop-shadow-lg">{title}</h1>
           <p className="text-slate-400 text-sm">Generated by InkFlow</p>
        </div>
        
        <div className="flex flex-wrap justify-center gap-3 relative z-50">
           {/* Edit Script */}
           <button onClick={onEditScript} className="p-2 text-slate-400 hover:text-white hover:bg-slate-800 rounded-lg transition-colors" title="Edit Script">
             <Pencil className="w-5 h-5" />
           </button>
           
           {/* Layout Selector */}
           <div className="relative">
             <button 
                onClick={() => { setShowLayoutMenu(!showLayoutMenu); setShowSaveMenu(false); }}
                className="bg-slate-800 hover:bg-slate-700 text-white px-4 py-2 rounded-lg font-bold flex items-center gap-2 border border-slate-700 transition-all"
             >
               <LayoutTemplate className="w-4 h-4" /> Layout
             </button>

             {showLayoutMenu && (
                <>
                  <div className="fixed inset-0 z-40" onClick={() => setShowLayoutMenu(false)}></div>
                  <div className="absolute right-0 top-full mt-2 w-56 bg-slate-800 border border-slate-700 rounded-xl shadow-2xl p-2 z-50 animate-in fade-in zoom-in-95 duration-200">
                    <div className="px-2 py-1 text-xs font-bold text-slate-500 uppercase tracking-wider mb-1">Templates</div>
                    
                    <button 
                      onClick={() => setLayout('grid')}
                      className={`w-full text-left px-3 py-2.5 rounded-lg text-sm font-medium transition-colors flex items-center gap-3 ${layout === 'grid' ? 'bg-purple-600 text-white' : 'text-slate-300 hover:bg-slate-700'}`}
                    >
                       <Grid2X2 className="w-4 h-4" />
                       <div className="flex flex-col">
                          <span>Classic Grid</span>
                          <span className="text-[10px] opacity-70">2 Columns</span>
                       </div>
                    </button>
                    
                    <button 
                      onClick={() => setLayout('vertical')}
                      className={`w-full text-left px-3 py-2.5 rounded-lg text-sm font-medium transition-colors flex items-center gap-3 ${layout === 'vertical' ? 'bg-purple-600 text-white' : 'text-slate-300 hover:bg-slate-700'}`}
                    >
                       <RectangleVertical className="w-4 h-4" />
                       <div className="flex flex-col">
                          <span>Webtoon Strip</span>
                          <span className="text-[10px] opacity-70">Vertical Scroll</span>
                       </div>
                    </button>
                    
                    <button 
                      onClick={() => setLayout('wide')}
                      className={`w-full text-left px-3 py-2.5 rounded-lg text-sm font-medium transition-colors flex items-center gap-3 ${layout === 'wide' ? 'bg-purple-600 text-white' : 'text-slate-300 hover:bg-slate-700'}`}
                    >
                       <Columns3 className="w-4 h-4" />
                       <div className="flex flex-col">
                          <span>Storyboard</span>
                          <span className="text-[10px] opacity-70">3 Columns</span>
                       </div>
                    </button>
                  </div>
                </>
             )}
           </div>

           {/* Save Menu */}
           <div className="relative">
             <button 
                onClick={() => { setShowSaveMenu(!showSaveMenu); setShowLayoutMenu(false); }}
                className="bg-yellow-500 hover:bg-yellow-400 text-black px-4 py-2 rounded-lg font-bold flex items-center gap-2 shadow-lg shadow-yellow-500/20 transition-all active:scale-95"
             >
               <Download className="w-4 h-4" /> Save <ChevronDown className={`w-4 h-4 transition-transform ${showSaveMenu ? 'rotate-180' : ''}`} />
             </button>

             {showSaveMenu && (
                <>
                  <div className="fixed inset-0 z-40" onClick={() => setShowSaveMenu(false)}></div>
                  <div className="absolute right-0 top-full mt-2 w-48 bg-slate-800 border border-slate-700 rounded-xl shadow-2xl p-1.5 z-50 animate-in fade-in zoom-in-95 duration-200">
                    <div className="px-3 py-2 text-xs font-bold text-slate-500 uppercase tracking-wider">Select Format</div>
                    
                    <button 
                      onClick={() => handleSave('png')}
                      disabled={isSaving}
                      className="w-full text-left text-slate-200 hover:bg-slate-700 hover:text-white px-3 py-2 rounded-lg text-sm font-medium transition-colors flex items-center gap-3"
                    >
                       {isSaving ? <Loader2 className="w-4 h-4 animate-spin text-purple-400"/> : <FileImage className="w-4 h-4 text-purple-400" />}
                       <span>PNG Image</span>
                       <span className="ml-auto text-[10px] bg-slate-900 px-1.5 py-0.5 rounded text-slate-400">HQ</span>
                    </button>
                    
                    <button 
                       onClick={() => handleSave('jpeg')}
                       disabled={isSaving}
                       className="w-full text-left text-slate-200 hover:bg-slate-700 hover:text-white px-3 py-2 rounded-lg text-sm font-medium transition-colors flex items-center gap-3"
                    >
                       {isSaving ? <Loader2 className="w-4 h-4 animate-spin text-blue-400"/> : <ImageIcon className="w-4 h-4 text-blue-400" />}
                       <span>JPG Image</span>
                       <span className="ml-auto text-[10px] bg-slate-900 px-1.5 py-0.5 rounded text-slate-400">Light</span>
                    </button>
                  </div>
                </>
             )}
           </div>
        </div>
      </div>

      <div ref={comicRef} className="bg-white p-4 md:p-8 rounded-sm shadow-2xl relative overflow-hidden transition-all duration-500">
        {/* Paper Texture Overlay */}
        <div className="absolute inset-0 bg-stone-100 opacity-50 pointer-events-none mix-blend-multiply"></div>
        
        {/* Dynamic Grid Layout */}
        <div className={`grid gap-4 relative z-10 transition-all duration-500 ${getLayoutClasses()}`}>
          {panels.map((panel, idx) => (
            <div 
                key={panel.id} 
                className={`relative group border-4 border-black bg-white shadow-[4px_4px_0px_rgba(0,0,0,1)] overflow-hidden transition-all duration-500 ${getPanelClasses(idx, panels.length)}`}
            >
              {/* Image Layer */}
              <div className="w-full h-full bg-slate-200 flex items-center justify-center relative overflow-hidden">
                 {panel.imageUrl ? (
                    <img src={panel.imageUrl} alt={panel.description} className="w-full h-full object-cover" />
                 ) : (
                    <div className="text-slate-400 text-center p-4">
                       {panel.isGenerating ? (
                          <RefreshCw className="w-8 h-8 animate-spin mx-auto mb-2 text-slate-800" />
                       ) : (
                          <div className="font-comic text-slate-300 text-4xl">?</div>
                       )}
                       <p className="text-xs font-mono text-slate-500 mt-2">{panel.isGenerating ? 'Drawing...' : 'Waiting'}</p>
                    </div>
                 )}
                 
                 {/* Regeneration Overlay (Hover) - Hidden during save */}
                 {!panel.isGenerating && !isSaving && (
                    <div className="absolute inset-0 bg-black/50 opacity-0 group-hover:opacity-100 transition-opacity flex items-center justify-center z-30">
                        <button 
                            onClick={() => onRegeneratePanel(panel.id)}
                            className="bg-white text-black px-4 py-2 rounded-full font-bold flex items-center gap-2 hover:scale-105 transition-transform"
                        >
                            <RefreshCw className="w-4 h-4" /> Redraw
                        </button>
                    </div>
                 )}
              </div>

              {/* Dialogue Bubble Layer */}
              {(panel.dialogue || panel.caption) && (
                  <div className="absolute inset-0 pointer-events-none p-4 flex flex-col justify-between z-20">
                     {/* Caption Top Left */}
                     {panel.caption && (
                        <div className="self-start bg-yellow-300 border-2 border-black px-3 py-1 shadow-[2px_2px_0px_rgba(0,0,0,1)] max-w-[80%] transform -rotate-1">
                           <p className="font-comic text-black text-xs md:text-sm uppercase font-bold tracking-wide leading-tight">
                              {panel.caption}
                           </p>
                        </div>
                     )}
                     
                     {/* Dialogue Bottom Right */}
                     {panel.dialogue && (
                        <div className={`
                           bg-white border-2 border-black px-4 py-2 rounded-[50%] shadow-[3px_3px_0px_rgba(0,0,0,0.5)] 
                           max-w-[70%] self-end relative mt-auto mb-4 mr-2
                        `}>
                            <p className="font-bubble text-black text-xs md:text-sm font-semibold text-center leading-snug">
                                {panel.dialogue}
                            </p>
                            {/* Little tail for bubble */}
                            <div className="absolute -bottom-2 right-4 w-4 h-4 bg-white border-b-2 border-r-2 border-black transform rotate-45"></div>
                        </div>
                     )}
                  </div>
              )}
              
              {/* Panel Number */}
              <div className="absolute top-0 left-0 bg-black text-white px-2 py-0.5 text-[10px] font-bold z-20">
                 {idx + 1}
              </div>
            </div>
          ))}
        </div>
        
        {/* Comic Footer */}
        <div className="mt-8 text-center border-t-2 border-black pt-4">
            <p className="font-comic text-black/50 text-sm">CREATED WITH INKFLOW & GEMINI</p>
        </div>
      </div>
    </div>
  );
};